### PR TITLE
fix local builds where signing configurations are not available.

### PR DESCRIPTION
**Pull request by williamwebb**

### CODE REVIEW

**Comment by martinbonnin** [comment]
How do I override the "arcane_tracker.signing" property in my local build ?

**Comment by williamwebb** [comment]
You want to create a `~/.gradle/gradle.propreties` file and place the value there.

**Comment by martinbonnin** [comment]
Can't make it work :-(. I tried echo "arcane_tracker.signing=true" > ~/.gradle/properties and then when trying to build in release, I get something like this: "The apk for your currently selected variant is not signed."

**Comment by williamwebb** [comment]
I will try locally. Do you know if `arcane_tracker.signing` is being resolved?

**Comment by martinbonnin** [comment]
Complete newbie in terms of gradle, sorry, how would I test that ? 
Or else something like this ? https://www.thoughtworks.com/insights/blog/signing-open-source-android-apps-without-disclosing-passwords

**Comment by williamwebb** [comment]
I tested this (added an exception inside the if block) and it should be working. I think you may have not have gotten the variable setup right.

**Comment by martinbonnin** [comment]
the full statement needed to be `signingConfig signingConfigs.mbonnin` and not just `signingConfigs.mbonnin`. I'm merging this and will fix it in master. 

Also, I'll move to https://www.thoughtworks.com/insights/blog/signing-open-source-android-apps-without-disclosing-passwords at some point.

**Comment by williamwebb** [comment]
Awesome. & i agree.

**Pull request merged**
