### PR TITLE
Fix/Suppress lint errors

### PR DESCRIPTION
**Pull request by williamwebb**

### CODE REVIEW

**Comment by williamwebb** [comment]
The new dependencies are to fix an issue with lambdas & lint described [here](https://github.com/evant/gradle-retrolambda#lint-fails-on-java-files-that-have-lambdas). The other changes [here](https://github.com/HearthSim/arcane_tracker/pull/25/files#diff-28d33285a7688929d6734252045f27dbR2) you should have been seeing. They are described [here](https://github.com/square/okio/issues/58).

**Comment by martinbonnin** [comment]
How can I see these lambdas & lint errors ? My Android studio inspection seems fine (AS 2.2.2). If I run lint from the command line, I get a load of errors but did not see anything okio or lambda related. 

I'm not against fixing lint warnings but I'd really like to get to the bottom of this as I haven't seen anything wrong from my side yet.

**Comment by williamwebb** [comment]
On you local run `~./gradlew clean build` and it will run through all the lint tasks and generate a report. I will also create a MR with travis-ci integration for future use and it will show these errors.

**Comment by martinbonnin** [comment]
Ok, I have an error now. I would have expected this to happen also when building from Android Studio, not only from the command line and also when building assembleDebug and not just 'build'.

Anyway, PR merged, thanks !

**Comment by martinbonnin** [comment]
Also, it would be interesting to understand how doing ./gradlew app:lint differs from what Android Studio is doing to display all the yellow tooltips etc.

**Pull request merged**
